#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# generate ostree in root
cd /
mkdir -p /ostree/repo
ostree init --repo=/ostree/repo
ostree remote add --set=gpg-verify=false fedora-atomic ${FEDORA_ATOMIC_TREE_URL}
ostree pull fedora-atomic ${FEDORA_ATOMIC_TREE_REF}
ostree remote delete fedora-atomic

mkdir /ostree/deploy
ostree admin os-init fedora-atomic
ostree admin deploy --os=fedora-atomic ${FEDORA_ATOMIC_TREE_REF} --karg-proc-cmdline --karg=selinux=0

# copy /etc/fstab to the deployed directory
SYSROOT=/ostree/deploy/fedora-atomic/deploy/${FEDORA_ATOMIC_TREE_REF}.0
cp /etc/fstab $SYSROOT/etc/

# need to find the generated images
DEPLOYED_DIRECTORY=$(find /boot/ostree -name fedora-atomic-* -type d)
DEPLOYED_ID=${DEPLOYED_DIRECTORY##*-}
INIT_IMAGE=$(find ${DEPLOYED_DIRECTORY} -name initramfs*.img)
VMLINUZ_IMAGE=$(find ${DEPLOYED_DIRECTORY} -name vmlinuz*)

DIB_IMAGE_ROOT_FS_UUID=$(uuidgen -r)

# generate ostree boot
cat > /etc/grub.d/15_ostree <<EOF
cat <<EOL
menuentry 'Fedora ${DIB_RELEASE} (ostree)' --class gnu-linux --class gnu --class os --unrestricted 'ostree-0-${DIB_IMAGE_ROOT_FS_UUID}' {
set gfxpayload=keep
insmod gzio
insmod part_msdos
insmod ext2
set root='hd0,msdos1'
if [ x\$feature_platform_search_hint = xy ]; then
  search --no-floppy --fs-uuid --hint='hd0,msdos1' --label ${DIB_ROOT_LABEL} --set=root ${DIB_IMAGE_ROOT_FS_UUID}
else
  search --no-floppy --fs-uuid --label ${DIB_ROOT_LABEL} --set=root ${DIB_IMAGE_ROOT_FS_UUID}
fi
linux16 ${VMLINUZ_IMAGE} no_timer_check console=tty1 console=ttyS0,115200n8 console=ttyAMA0 console=hvc0 net.ifnames=0 root=LABEL=${DIB_ROOT_LABEL} ostree=/ostree/boot.1/fedora-atomic/${DEPLOYED_ID}/0
initrd16 ${INIT_IMAGE}
}
EOL
EOF
chmod +x /etc/grub.d/15_ostree

# start cloud-init on boot
ln -sf $SYSROOT/usr/lib/systemd/system/cloud-config.service $SYSROOT/etc/systemd/system/multi-user.target.wants/cloud-config.service
ln -sf $SYSROOT/usr/lib/systemd/system/cloud-final.service $SYSROOT/etc/systemd/system/multi-user.target.wants/cloud-final.service
ln -sf $SYSROOT/usr/lib/systemd/system/cloud-init.service $SYSROOT/etc/systemd/system/multi-user.target.wants/cloud-init.service
ln -sf $SYSROOT/usr/lib/systemd/system/cloud-init-local.service $SYSROOT/etc/systemd/system/multi-user.target.wants/cloud-init-local.service

# disabled docker-storage-setup
rm $SYSROOT/etc/systemd/system/multi-user.target.wants/docker-storage-setup.service

# remove previous entry and generate config
rm /etc/grub.d/10_linux
grub2-mkconfig -o /boot/grub2/grub.cfg

# remove non usable images
rm -rf /boot/vmlinuz*
rm -rf /boot/initramfs*
